---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fugi0485/lapanoplidemeli.fugi0485.odns.fr/
    - cp -R $DEPLOYPATH/public/uploads ./public/
    - rm -rf $DEPLOYPATH/*
    - cp -R *  $DEPLOYPATH
    - cp .env.local $DEPLOYPATH/.env
    - cd $DEPLOYPATH
    - composer install
    - php bin/console do:mi:mi -n