---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fugi0485/lapanopliedemeli.fr/
    - /bin/cp -R $DEPLOYPATH/public/uploads ./public/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R *  $DEPLOYPATH
    - /bin/cp .env.local $DEPLOYPATH/.env
#    - composer install --working-dir=$DEPLOYPATH
    - php $DEPLOYPATH/bin/console do:mi:mi -n